-   id: django-uncommitted-migrations
    name: Check for uncommitted Django migrations
    description: Check unstaged files for a Migration class and stop the commit
    entry: check_migrations
    language: python
    language_version: python3
    always_run: true
    types: [text]
